version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      patch-updates:
        update-types:
          - "patch"
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions-updates:
        patterns:
          - "*"
    cooldown:
      default-days: 7
